FROM bioconductor/devel_core2:latest
RUN useradd -ms /bin/bash trena
COPY . /home/trena/tmp
WORKDIR /home/trena
#RUN R CMD INSTALL /home/trena/tmp/Demo_0.99.0.tar.gz
RUN sudo apt-get install apt-utils -y
RUN sudo apt-get install libpq-dev -y
#RUN sudo apt-get install libmysqlclient-dev -y
RUN cat /home/trena/tmp/myBashCustomizations >> /home/trena/.bashrc
RUN cat /home/trena/tmp/.Rprofile > /home/trena/.Rprofile
USER trena
RUN mkdir /home/trena/library
USER root
RUN Rscript -e "biocGet('lassopv')"
RUN Rscript -e "biocGet('glmnet')"
RUN Rscript -e "biocGet('randomForest')"
RUN Rscript -e "biocGet('flare')"
RUN Rscript -e "biocGet('vbsr')"
RUN Rscript -e "biocGet('RPostgreSQL')"
#RUN Rscript -e "biocGet('RMySQL')"
RUN Rscript -e "biocGet('BSgenome.Hsapiens.UCSC.hg38')"
RUN Rscript -e "biocGet('BSgenome.Mmusculus.UCSC.mm10')"
RUN Rscript -e "biocGet('org.Hs.eg.db')"
RUN Rscript -e "biocGet('org.Mm.eg.db')"
RUN Rscript -e "biocGet('SNPlocs.Hsapiens.dbSNP150.GRCh38')"


