FROM trena_prelims:latest
#FROM bioconductor/devel_core2:latest
USER root
RUN apt-get -y install libzmq3-dev
#RUN useradd -ms /bin/bash trena
RUN mkdir -p /home/trena/work
RUN mkdir -p /home/trena/library
RUN chown -R trena /home/trena
#user trena
COPY . /home/trena/work
RUN Rscript -e "biocGet('rzmq')"
